var quotes = [
	"I've been quite open about this around the office: I don't want this parks department to build any parks, because I don't believe in government. I think that all government is a waste of taxpayer money. My dream is to have the park system privatized and run entirely for profit by corporations, like Chuck E. Cheese. They have an impeccable business model. I would rather work for Chuck E. Cheese.",
	"My ex-wife Tammy cheated on me, then we divorced, then last week I ran into her sister Beth here; turns out she hates Tammy too, so we started dating. It's like a fairy tale.",
	"On my deathbed, my final wish is to have my ex-wives rush to my side so I can use my dying breath to tell them both to go to hell one last time.",
	"I got my first job when I was 9. Worked at a sheet metal factory. In two weeks, I was running the floor. Child labor laws are ruining this country.",
	"I have cried twice in my life. Once when I was seven and I was hit by a school bus. And then again when I heard that Li'l Sebastian had passed.",
	"I think if you would know one thing about me it would be that I prefer laying wreaths to lighting torches.",
	"It's never too early to learn that the government is a greedy piglet that suckles on a taxpayer's teet until they have sore, chapped nipples. I'm gonna need a different metaphor to give this nine year old.",
	"I won't publicly endorse a product unless I use it exclusively and I really believe in it. My only official recommendations are US Army issued mustache trimmers, Morton's Salt, and the C.R. Lawrence fine two inch style oscillating knife blade.",
	"I don't like loud noises and people making a fuss. And I especially don't like people celebrating, because they know a piece of private information about me. Plus the whole thing is a scam. Birthdays were invented by Hallmark to sell cards.",
	"The key to burning an ex-wife effigy is to dip it in paraffin wax and then toss the flaming bottle of isopropyl alcohol from a safe distance. Do not stand too close when you light an ex-wife effigy.",
	"[regarding turkey burgers] Is that a fried turkey leg inside a grilled hamburger? If so, yes, delicious.",
	"Here's mine. It's a hamburger made out of meat on a bun with nothing. Add ketchup if you want I couldn't care less.",
	"The dentist pulled the tooth out yesterday but it's always a good idea to demonstrate to your coworkers that you are capable of withstanding a tremendous amount of pain. Plus, it's always fun to see Tom faint.",
	"[on fishing] It's like yoga, except I still get to kill something.",
	"What the fuck is a German muffin?!",
	"It's called the 'ground' when it's outside.",
	"All of you be quiet. Andy, she's mad because you said 'awesome sauce' instead of 'I love you too.' April, he loves you. Stop being a child. Tom, you're clearly at fault here. Blaming Jerry won't save you. Jerry, we both know you were shotgunning funnel cakes instead of watching Lil Sebastian. So everyone apologize to everyone else.",
	"When I'm done eating a Mulligan's meal, for weeks afterwards, there are flecks of meat in my mustache. And I refuse to clean it because every now and then a piece of meat will fall into my mouth.",
	"The less I know about other people's affairs, the happier I am. I'm not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.",
	"Haircuts, there are three acceptable haircuts: High and tight, crew cut, buzz cut. Are the scissors broken in your house, son?",
	"I have been developing the Swanson Pyramid of Greatness for years. It's a perfectly calibrated recipe for maximum personal achievement. Categories include: Capitalism, God's way of determining who is smart, and who is poor. Crying, acceptable at funerals and the Grand Canyon. Rage. Poise. Property rights. Fish, for sport only, not for meat. Fish meat is practically a vegetable.",
	"Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons.",
	"Well, I am not usually one for speeches. So, goodbye.",
	"Right off the bat, we sell city hall. Let somebody turn it into a large gas station or a TJ Maxx.",
	"I'm an official member of a task force dedicated to slashing the city budget. Just saying that gave me a semi.",
	"Give a man a fish and you feed him for a day. Don't teach a man to fish, and you feed yourself. He's a grown man. Fishing's not that hard.",
	"I have to nap up. If I don't get a solid five, it kills my sunny disposition.",
	"April was supposed to be the moat that kept the citizen barbarians away from Swanson castle. Instead she blew up the castle and stabbed me in the face.",
	"Leslie, my first wife Tammy tried throwing me a surprise birthday party . When I saw my friends hiding through the window, I drove to a gas station, called the cops and told them people had broken into my home. I'm not big on surprises.",
	"Those dates are arbitrary. They're like those expiration dates that the government forces companies to put on yogurt and medicine.",
	"Be proud of yourself. You deserve an award. Not this one, obviously. This one belongs to me. But some other one. Some other lesser award.",
	"Swansons have a preternaturally high tolerance for alcohol. My old man used to put Wild Turkey on his cornflakes.",
	"The whole point of this country is if you want to eat garbage, balloon up to 600 pounds and die of a heart attack at 43, you can! You are free to do so. To me, that's beautiful.",
	"I think the entire government should be privatized. Chuck E. Cheese could run the parks. Everything operated by tokens. Drop in a token, go on the swing set. Drop in another token, take a walk. Drop in a token, look at a duck.",
	"If I wanted to bring a large number of deviled eggs, but I didn't want to share them with anyone else, can you guarantee fridge space?",
	"Strippers do nothing for me. I like a strong, salt of the Earth, self-possessed woman at the top of her field. Your Steffi Grafs, your Sheryl Swoopeses, but I will take a free breakfast buffet anytime, anyplace.",
];
